version: '2'
services:

  applications:
    image: tianon/true

  workspace:
    build:
      context: ./workspace
      args:
        - RUBY_VERSION=${WORKSPACE_RUBY_VERSION}
        - INSTALL_NODE=${WORKSPACE_INSTALL_NODE}
        - INSTALL_YARN=${WORKSPACE_INSTALL_YARN}
        - INSTALL_LINUXBREW=${WORKSPACE_INSTALL_LINUXBREW}
        - INSTALL_PYTHON=${WORKSPACE_INSTALL_PYTHON}
        - INSTALL_IMAGEMAGICK=${WORKSPACE_INSTALL_IMAGEMAGICK}
        - PUID=${WORKSPACE_PUID}
        - PGID=${WORKSPACE_PGID}
        - NODE_VERSION=${WORKSPACE_NODE_VERSION}
        - YARN_VERSION=${WORKSPACE_YARN_VERSION}
        - TZ=${WORKSPACE_TIMEZONE}
    volumes_from:
      - applications
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
    tty: true
    networks:
      - frontend
      - backend

  mariadb:
    build: ./mariadb
    volumes:
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - backend

  nginx:
    build: ./nginx
    volumes_from:
      - applications
    volumes:
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
      - frontend
      - backend
  mailu-front:
    image: mailu/nginx:${MAILU_VERSION}
    environment:
      - ADMIN=${MAILU_ADMIN}
      - WEB_ADMIN=${MAILU_WEB_ADMIN}
      - WEB_WEBMAIL=${MAILU_WEB_WEBMAIL}
      - WEBDAV=${MAILU_WEBDAV}
      - HOSTNAMES=${MAILU_HOSTNAMES}
      - TLS_FLAVOR=${MAILU_TLS_FLAVOR}
      - MESSAGE_SIZE_LIMIT=${MAILU_MESSAGE_SIZE_LIMIT}
    ports:
      - "${MAILU_HTTP_PORT}:80"
      - "${MAILU_HTTPS_PORT}:443"
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
      - "25:25"
      - "465:465"
      - "587:587"
    volumes:
      - "${DATA_PATH_HOST}/mailu/certs:/certs"
    networks:
      backend:
        aliases:
          - front
  mailu-imap:
    image: mailu/dovecot:${MAILU_VERSION}
    environment:
      - DOMAIN=${MAILU_DOMAIN}
      - HOSTNAMES=${MAILU_HOSTNAMES}
      - POSTMASTER=${MAILU_POSTMASTER}
      - WEBMAIL=${MAILU_WEBMAIL}
      - RECIPIENT_DELIMITER=${MAILU_RECIPIENT_DELIMITER}
    volumes:
      - "${DATA_PATH_HOST}/mailu/data:/data"
      - "${DATA_PATH_HOST}/mailu/mail:/mail"
      - "${DATA_PATH_HOST}/mailu/overrides:/overrides"
    depends_on:
      - mailu-front
    networks:
      backend:
        aliases:
          - imap
  mailu-smtp:
    image: mailu/postfix:${MAILU_VERSION}
    environment:
      - DOMAIN=${MAILU_DOMAIN}
      - HOSTNAMES=${MAILU_HOSTNAMES}
      - RELAYHOST=${MAILU_RELAYHOST}
      - RELAYNETS=${MAILU_RELAYNETS}
      - RECIPIENT_DELIMITER=${MAILU_RECIPIENT_DELIMITER}
      - MESSAGE_SIZE_LIMIT=${MAILU_MESSAGE_SIZE_LIMIT}
    volumes:
      - "${DATA_PATH_HOST}/mailu/data:/data"
      - "${DATA_PATH_HOST}/mailu/overrides:/overrides"
    depends_on:
      - mailu-front
    networks:
      backend:
        aliases:
          - smtp

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
